version: '3.9'
#This is a test 4
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: >
      bash -c "./wait-for-it.sh db:3306 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=simpleapp_db
      - DB_USER=test
      - DB_PASSWORD=test123
      - DB_HOST=db
      - DB_PORT=3306

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: simpleapp_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: test123
    ports:
      - "3306:3306"

volumes:
  mysql_data:
