# Generated by Django 4.2.17 on 2025-01-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleApp', '0003_alter_number_value'),
    ]

    operations = [
    ]
