# Generated by Django 4.2.17 on 2025-01-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleApp', '0004_populate_number_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
